### ISSUE TITLE
blog-view example doesn't work

### ISSUE THREAD

**Issue by blsnttt** [keystonejs-contrib/keystonejs-contrib#5]
Hey! I was working on a project based on the blog-view example. While trying to a test heroku deploy, I saw the remote build failed, while the local build completed just fine.

I've then tried deleting the local yarn.lock and modules folder and reinstalling everything again, and the build does in fact fail. I'm guessing something changed in the required dependencies?

If I try and place the old yarn.lock and modules folder back again, the app builds just fine again. Also trying a fresh copy of the blog-view example throws the same error, so some package update must be causing this. I've attached  below the error being thrown by the console

```
TypeError: keystone.getResolvers is not a function
    at createApolloServer (C:\%projectfolder%\node_modules\@keystonejs\app-graphql\lib\apolloServer.js:148:25)
    at GraphQLApp.prepareMiddleware (C:\%projectfolder%\node_modules\@keystonejs\app-graphql\index.js:23:20)
    at C:\%projectfolder%\node_modules\@keystonejs\keystone\lib\Keystone\index.js:752:17
    at Array.map (<anonymous>)
    at Keystone.prepare (C:\%projectfolder%\node_modules\@keystonejs\keystone\lib\Keystone\index.js:751:12)
    at executeDefaultServer (C:\%projectfolder%\node_modules\@keystonejs\keystone\bin\utils.js:112:42)
error Command failed with exit code 1.
```

**Comment by gautamsi** [comment]
have you checked out this - https://www.keystonejs.com/guides/heroku/#deploying-keystone-to-heroku?

are you using express view with template stuff or want to work on nextjs based setup?

**Comment by blsnttt** [comment]
> have you checked out this - https://www.keystonejs.com/guides/heroku/#deploying-keystone-to-heroku?
> 
> are you using express view with template stuff or want to work on nextjs based setup?

hey @gautamsi, thanks for the answer

I'm using the express view with the pug templating one for different projects, but maybe I've explained myself a little backwards. I've succesfully deployed Keystone to Heroku before, the problem is something changed in the blog-view example dependencies, at least for the express view.

### To reproduce:
1. clone blog-view
1. run `yarn` then `yarn dev` on the blog-view example. The dev server fails to start and this console error shows up:

> ```
> TypeError: keystone.getResolvers is not a function
>     at createApolloServer (C:\%projectfolder%\node_modules\@keystonejs\app-graphql\lib\apolloServer.js:148:25)
>     at GraphQLApp.prepareMiddleware (C:\%projectfolder%\node_modules\@keystonejs\app-graphql\index.js:23:20)
>     at C:\%projectfolder%\node_modules\@keystonejs\keystone\lib\Keystone\index.js:752:17
>     at Array.map (<anonymous>)
>     at Keystone.prepare (C:\%projectfolder%\node_modules\@keystonejs\keystone\lib\Keystone\index.js:751:12)
>     at executeDefaultServer (C:\%projectfolder%\node_modules\@keystonejs\keystone\bin\utils.js:112:42)
> error Command failed with exit code 1.
> ```

What I was trying to say earlier is: on projects where I already have a `yarn.lock` and `node_modules` it doesn't throw any error and the dev server, start and build commands work correctly, I think because the local packages that are present are older and still work properly.

However, in these existing working projects, if I remove `yarn.lock`, `node_modules` and reinstall the packages via `yarn` and start the dev server again, the error shows up and there's no way to get it building again, unless you put back the old `yarn.lock` and `node_modules`. This is preventing me from pushing updates on Heroku for existing projects.

This brought me to downloading the blog-view again, and noting the problem is there even out of the box.

When pushing to heroku as a fresh installation, the remote deployment throws the exact same error, leading me to believe both heroku and fresh local installs are no longer working because of some new dependency change?

**Comment by gautamsi** [comment]
see this PR https://github.com/keystonejs-contrib/keystonejs-contrib/pull/6
I tried this with heroku, I knew that keystone versions need upgrade which I did before trying heroku. I used above link for heroku deployment. 

I also had to set some env variables 
![image](https://user-images.githubusercontent.com/5769869/82954231-ef48f400-9fc9-11ea-83c6-94a50f663e74.png)

also needed to change engine config to use yarn see updated package.json 
```json
 "engines": {
    "node": "12.16.x",
    "yarn": "1.x"
  },
```

**Comment by gautamsi** [comment]
I have also created this on heroku on https://test-keystone-blog-view.herokuapp.com/ once yu are done, I will be turning off the dyno as this is not very secure app.

**Comment by gautamsi** [comment]
@blsnttt let me know if you still have any problem with this.

**Comment by blsnttt** [comment]
@gautamsi thank you very much for the steady help! In the end I've ended up migrating to Nuxt along with Keystone for additional reasons, but at least now my other projects build correctly.
